# Generated by Django 5.1.3 on 2024-11-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_jour', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Scène',
                'verbose_name_plural': 'Scènes',
            },
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artiste_images/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backofficeNationSound77.style')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backofficeNationSound77.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.TimeField()),
                ('calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backofficeNationSound77.calendrier')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backofficeNationSound77.event')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backofficeNationSound77.scene')),
            ],
            options={
                'ordering': ['calendrier', 'horaire'],
            },
        ),
    ]
