# Generated by Django 5.1.3 on 2024-11-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0002_calendrier_scene_artiste_event_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
