# Generated by Django 5.1.3 on 2024-11-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0007_alter_artiste_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriePoi', models.CharField(max_length=20)),
                ('imagePoi', models.ImageField(upload_to='poi_images/')),
            ],
            options={
                'ordering': ['categoriePoi'],
            },
        ),
        migrations.CreateModel(
            name='ListePOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPOI', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nomPOI'],
            },
        ),
        migrations.AlterField(
            model_name='artiste',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
