# Generated by Django 5.1.3 on 2024-11-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0010_categoriepoi_urlpoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPoi', models.CharField(max_length=50)),
                ('latitudePoi', models.DecimalField(decimal_places=20, max_digits=20)),
                ('longitudePoi', models.DecimalField(decimal_places=20, max_digits=20)),
            ],
            options={
                'ordering': ['nomPoi'],
            },
        ),
        migrations.DeleteModel(
            name='NomPoi',
        ),
        migrations.AlterField(
            model_name='categoriepoi',
            name='urlPoi',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='poi',
            name='categoriePoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backofficeNationSound77.categoriepoi'),
        ),
    ]
