# Generated by Django 5.1.3 on 2024-11-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0011_poi_delete_nompoi_alter_categoriepoi_urlpoi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={},
        ),
    ]
