# Generated by Django 5.1.3 on 2024-11-12 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0012_alter_poi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'ordering': ['nomPoi']},
        ),
        migrations.AddField(
            model_name='poi',
            name='descriptionPoi',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poi',
            name='latitudePoi',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='poi',
            name='longitudePoi',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
