# Generated by Django 5.1.3 on 2024-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0013_alter_poi_options_poi_descriptionpoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='descriptionPoi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
