# Generated by Django 5.1.3 on 2024-11-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0015_rename_image_artiste_visuel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendrier',
            options={'ordering': ['jour_festival']},
        ),
        migrations.RenameField(
            model_name='calendrier',
            old_name='no_jour',
            new_name='jour_festival',
        ),
    ]
