# Generated by Django 5.1.3 on 2024-11-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0016_alter_calendrier_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendrier',
            old_name='date',
            new_name='date_festival',
        ),
    ]
