# Generated by Django 5.1.3 on 2024-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0017_rename_date_calendrier_date_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUrgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgUrgent', models.CharField(max_length=100)),
                ('prioriteMsg', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['prioriteMsg', 'msgUrgent'],
            },
        ),
    ]
