# Generated by Django 5.1.3 on 2024-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0018_messageurgent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=100)),
                ('prioriteInfo', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['prioriteInfo', 'information'],
            },
        ),
    ]
