# Generated by Django 5.1.3 on 2024-11-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0019_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carrousel_images/')),
                ('prioriteImage', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['prioriteImage'],
            },
        ),
    ]
