# Generated by Django 5.1.3 on 2024-11-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backofficeNationSound77', '0020_imagecarrousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecarrousel',
            options={'ordering': ['prioriteImage'], 'verbose_name_plural': 'Images Carrousel'},
        ),
        migrations.AlterModelOptions(
            name='messageurgent',
            options={'ordering': ['prioriteMsg', 'msgUrgent'], 'verbose_name_plural': 'Messages urgents'},
        ),
    ]
