# Generated by Django 5.1.3 on 2024-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('visuel', models.ImageField(upload_to='partenaires_images/')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
