# Generated by Django 5.1.3 on 2024-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionLegale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('mention', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
