# Generated by Django 5.1.3 on 2024-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0002_mentionlegale_alter_partenaire_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuel', models.ImageField(blank=True, null=True, upload_to='contacts_images/')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('horaires', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='mentionlegale',
            options={'ordering': ['titre'], 'verbose_name_plural': 'Mentions Légales'},
        ),
    ]
