# Generated by Django 5.1.3 on 2024-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0004_rename_tel_contact_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('réponse', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
