# Generated by Django 5.1.3 on 2024-11-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0007_faq_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenairecategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['categorie'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['categorie', 'ordre']},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['categorie', 'nom']},
        ),
        migrations.AlterField(
            model_name='faq',
            name='réponse',
            field=models.TextField(max_length=700),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecransReact.partenairecategorie'),
            preserve_default=False,
        ),
    ]
