# Generated by Django 5.1.3 on 2024-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0008_partenairecategorie_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentionlegale',
            options={'ordering': ['ordre', 'titre'], 'verbose_name_plural': 'Mentions Légales'},
        ),
        migrations.AddField(
            model_name='mentionlegale',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='faq',
            name='réponse',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mentionlegale',
            name='mention',
            field=models.TextField(max_length=1000),
        ),
    ]
