# Generated by Django 5.1.3 on 2024-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0009_alter_mentionlegale_options_mentionlegale_ordre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentionlegale',
            name='ordre',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
