# Generated by Django 5.1.3 on 2024-11-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0011_alter_mentionlegale_ordre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='réponse',
            new_name='reponse',
        ),
    ]
