# Generated by Django 5.1.3 on 2024-11-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecransReact', '0012_rename_réponse_faq_reponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordre']},
        ),
    ]
